/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import Modele.*;
import Controleur.Moniteur;
import Controleur.Tableau;
import Controleur.Tiers;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView;

/**
 *
 * @author Maxime
 */
public class VueGestionMoniteur extends javax.swing.JPanel {

    private JTable tableMoniteurs;
    private Tableau unTableau ;
    public VueGestionMoniteur() {
        initComponents();
        
	this.editMatricule.setEditable(false);
        
       String entetes [] = {"Matricule","Nom","Prenom","Login","Email","Telephone"} ;
        Object donnees [] [] = this.remplirDonnees();//object elle n'a pass de type, peut etre n'importe quoi
        //instaciation de la classe Tableau
        this.unTableau = new Tableau(donnees,entetes);
        //instanciaton de la jtable avec l'objet modele de table

        this.tableMoniteurs = new JTable(this.unTableau);
        JScrollPane uneScroll =new JScrollPane(tableMoniteurs);
        uneScroll.setBounds(70, 150, 550, 150);
        this.setBounds(50, 100, 750, 350);
        
        this.add(uneScroll);
        this.tableMoniteurs.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                int ligne = tableMoniteurs.getSelectedRow();
                editMatricule.setText(tableMoniteurs.getValueAt(ligne, 0).toString());
                editNom.setText(tableMoniteurs.getValueAt(ligne, 1).toString());
                editPrenom.setText(tableMoniteurs.getValueAt(ligne, 2).toString());
                editLogin.setText(tableMoniteurs.getValueAt(ligne, 3).toString());
                editEmail.setText(tableMoniteurs.getValueAt(ligne, 4).toString());
                editTelephone.setText(tableMoniteurs.getValueAt(ligne, 5).toString());
                
                
             
            }

            @Override
            public void mousePressed(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                int ligne = tableMoniteurs.getSelectedRow();
                editMatricule.setText(tableMoniteurs.getValueAt(ligne, 0).toString());
                editNom.setText(tableMoniteurs.getValueAt(ligne, 1).toString());
                editPrenom.setText(tableMoniteurs.getValueAt(ligne, 2).toString());
                editLogin.setText(tableMoniteurs.getValueAt(ligne, 3).toString());
                editEmail.setText(tableMoniteurs.getValueAt(ligne, 4).toString());
                editTelephone.setText(tableMoniteurs.getValueAt(ligne, 5).toString());
                 //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        }
        );
             this.setVisible(false);
                }

                
    /**
     * This method is calledrom within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        rechercheNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recherchePrenom = new javax.swing.JTextField();
        btRechercher = new javax.swing.JButton();
        btEditer = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();
        editNom = new javax.swing.JTextField();
        editPrenom = new javax.swing.JTextField();
        editLogin = new javax.swing.JTextField();
        editEmail = new javax.swing.JTextField();
        editTelephone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editMatricule = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btSupprimer = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        rechercheNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheNomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Prénom :");
        jLabel2.setToolTipText("");

        recherchePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherchePrenomActionPerformed(evt);
            }
        });

        btRechercher.setBackground(new java.awt.Color(0, 0, 204));
        btRechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btRechercher.setText("Rechercher");
        btRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechercherActionPerformed(evt);
            }
        });

        btEditer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Actions-document-edit-icon.png"))); // NOI18N
        btEditer.setText("Editer");
        btEditer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditerActionPerformed(evt);
            }
        });

        btAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close-2-icon 2(1).png"))); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        editLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLoginActionPerformed(evt);
            }
        });

        editTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTelephoneActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom :");

        jLabel4.setText("Prénom :");

        jLabel5.setText("Login :");

        jLabel6.setText("Email :");

        jLabel7.setText("Telephone :");

        editMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMatriculeActionPerformed(evt);
            }
        });

        jLabel8.setText("Matricule :");

        btSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Recycle-Bin-icon.png"))); // NOI18N
        btSupprimer.setText("Supprimer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(editMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btAnnuler)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(recherchePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rechercheNom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSupprimer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(editPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(editLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(editTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRechercher)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btEditer, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rechercheNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recherchePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btRechercher)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btEditer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btAnnuler)
                                .addComponent(btSupprimer))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheNomActionPerformed

    private void recherchePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherchePrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePrenomActionPerformed

    private void btEditerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditerActionPerformed
        if(editMatricule.getText().equals(""))
        {
                JOptionPane.showMessageDialog(this, "Veuillez renseigner d'Id Client");
        }
        else {

        
        String nom = this.editNom.getText();
        String prenom = this.editPrenom.getText();
        String login = this.editLogin.getText();
        String email = this.editEmail.getText();
        String telephone = this.editTelephone.getText();
        
        

        //instanciation du client
        Moniteur unMoniteur =(Moniteur) Modele.selectWhereTiers(editMatricule.getText());
        unMoniteur.setLogin(login);
        unMoniteur.setEmail(email);
        unMoniteur.setPrenom(prenom);
        unMoniteur.setTelephone(telephone);
        unMoniteur.setNom(nom);
        //appel  du Modele pour inserer un client dans la BDD
        Modele.updateTiers(unMoniteur);
        JOptionPane.showMessageDialog(this, "Mise à jour reussie !");
        }
    }//GEN-LAST:event_btEditerActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.editNom.setText("");
        this.editPrenom.setText("");
        this.editEmail.setText("");
        this.editTelephone.setText("");
        this.editLogin.setText("");
        
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void btRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRechercherActionPerformed

    private void editTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTelephoneActionPerformed

    private void editLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editLoginActionPerformed

    private void editMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMatriculeActionPerformed

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt)
    {
        if(editMatricule.getText().equals(""))
        {
                JOptionPane.showMessageDialog(this, "Veuillez renseigner d'Id Client");
        }
        else {
       
        Moniteur unMoniteur =(Moniteur) Modele.selectWhereTiers(editMatricule.getText());
        Modele.deleteTiers(unMoniteur);
        JOptionPane.showMessageDialog(this, "Suppression reussie !");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btEditer;
    private javax.swing.JButton btRechercher;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JTextField editEmail;
    private javax.swing.JTextField editLogin;
    private javax.swing.JTextField editMatricule;
    private javax.swing.JTextField editNom;
    private javax.swing.JTextField editPrenom;
    private javax.swing.JTextField editTelephone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField rechercheNom;
    private javax.swing.JTextField recherchePrenom;
    // End of variables declaration//GEN-END:variables




	public Object [] [] remplirDonnees()
	{
		ArrayList<Moniteur> lesMoniteurs = Modele.selectAllMoniteurs();
		Object donnees [] [] = new Object [lesMoniteurs.size()] [6];
		int i = 0;
		for (Moniteur unMoniteur : lesMoniteurs)
		{
			donnees[i] [0] = unMoniteur.getUnMatricule()+ "";
                        donnees[i] [1] = unMoniteur.getNom();
			donnees[i] [2] = unMoniteur.getPrenom();
			donnees[i] [3] = unMoniteur.getLogin();
			donnees[i] [4] = unMoniteur.getEmail();
                        donnees[i] [5] = unMoniteur.getTelephone();
			i++;
		}
		return donnees;
	}



}
